#include <stdio.h>

int main() {
    int salary;

    printf("Zadejte výši příjmu: ");
    scanf("%d", &salary);

    float rate1 = 0.1, rate2 = 0.2, rate3 = 0.3;
    float tax1 = 0, tax2 = 0, tax3 = 0;
    int limit1 = 10000, limit2 = 20000;

    if (salary < limit1) {
        tax1 = salary * rate1;
    } else if (salary <= limit2) {
        tax1 = limit1 * rate1;
        tax2 = (salary - limit1) * rate2;
    } else {
        tax1 = limit1 * rate1;
        tax2 = (limit2 - limit1) * rate2;
        tax3 = (salary - limit2) * rate3;
    }


    printf("\n\nPlat: %d; daň: %.2f\n", salary, tax1 + tax2 + tax3);



    /**
     *  generated by chatGPT
     */

    /*
    float mzda = salary;
    float dan;

    if (mzda <= 10000) {
        dan = mzda * 0.1;
    } else if (mzda <= 20000) {
        dan = 1000 + (mzda - 10000) * 0.2;
    } else {
        dan = 3000 + (mzda - 20000) * 0.3;
    }

    printf("Progresivní daň ze mzdy %.2f Kč je %.2f Kč.\n", mzda, dan);
     */
    return 0;
}
